baseURL = "https://www.bromberger.com/"
defaultContentLanguage = "en"
title = "Seth Bromberger | Critical Infrastructure Security"
theme = "congo"
enableGitInfo = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true
