colorScheme = "congo"
defaultAppearance = "light"
autoSwitchAppearance = true

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showDate = false
  showReadingTime = false
  showAuthor = false
  showBreadcrumbs = true

[author]
  name = "Seth Bromberger"
  image = "img/avatar.png"
  headline = "M.S. Eng. · CISSP-ISSMP · CISM · NSA-IAM"
  bio = "Educator and security practitioner with three decades protecting critical infrastructure for Fortune 500 companies and federal agencies and conducting security research at national laboratories. Dedicated to developing the next generation of information security leaders."
  links = [
    { github = "https://github.com/sbromberger" },
    { researchgate = "https://www.researchgate.net/profile/Seth-Bromberger" }
  ]

[footer]
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
